G5_C23319/urls.py
import statistics
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls.static import static
from django.conf import settings
from administracion.admin import rn_admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rnadmin/', rn_admin.urls),
    path('', include('publica.urls')),
    path('administracion/',include('administracion.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

administracion/urls.py
from django.urls import path
from . import views
from .views import NaturalParkListView, NaturalParkCreateView,NaturalParkUpdateView, NaturalParkDeleteView, CategoryListView, CategoryCreateView, CategoryUpdateView, CategoryDeleteView, CampsiteListView, CampsiteCreateView, CampsiteUpdateView, CampsiteDeleteView, AvailabilityListView, AvailabilityCreateView, AvailabilityUpdateView, AvailabilityDeleteView, ProfileListView, ProfileCreateView, ProfileUpdateView, ProfileDeleteView, ReservationListView, ReservationCreateView, ReservationDeleteView, ReservationUpdateView, GuestListView, GuestDeleteView, GuestUpdateView

urlpatterns = [
    path('', views.index_admin, name='inicio_admin'),
    #path('clientes/listar/', views.listar_clientes, name='listar_clientes'),
    path('naturalparks/', NaturalParkListView.as_view(), name='naturalpark_list'),
    path('naturalparks/create/', NaturalParkCreateView.as_view(), name='naturalpark_create'),
    path('naturalparks/update/<int:pk>/', NaturalParkUpdateView.as_view(), name='naturalpark_update'),
    path('naturalparks/delete/<int:pk>/', NaturalParkDeleteView.as_view(), name='naturalpark_delete'),
    path('categories/', CategoryListView.as_view(), name='category_list'),
    path('categories/create/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),
    path('campsites/', CampsiteListView.as_view(), name='campsite_list'),
    path('campsites/create/', CampsiteCreateView.as_view(), name='campsite_create'),
    path('campsites/update/<int:pk>/', CampsiteUpdateView.as_view(), name='campsite_update'),
    path('campsites/delete/<int:pk>/', CampsiteDeleteView.as_view(), name='campsite_delete'),
    path('availabilities/', AvailabilityListView.as_view(), name='availability_list'),
    path('availabilities/create/', AvailabilityCreateView.as_view(), name='availability_create'),
    path('availabilities/update/<int:pk>/', AvailabilityUpdateView.as_view(), name='availability_update'),
    path('availabilities/delete/<int:pk>/', AvailabilityDeleteView.as_view(), name='availability_delete'),
    path('profiles/', ProfileListView.as_view(), name='profile_list'),
    path('profiles/create/', ProfileCreateView.as_view(), name='profile_create'),
    path('profiles/<int:pk>/update/', ProfileUpdateView.as_view(), name='profile_update'),
    path('profiles/<int:pk>/delete/', ProfileDeleteView.as_view(), name='profile_delete'),
    path('reservations/', ReservationListView.as_view(), name='reservation_list'),
    path('reservations/create/', ReservationCreateView.as_view(), name='reservation_create'),
    path('reservations/update/<int:pk>/', ReservationUpdateView.as_view(), name='reservation_update'),
    path('reservations/delete/<int:pk>/', ReservationDeleteView.as_view(), name='reservation_delete'),
    path('guests/', GuestListView.as_view(), name='guest_list'),
    #path('guests/create/', GuestCreateView.as_view(), name='guest_create'),
    path('guests/update/<int:pk>/', GuestUpdateView.as_view(), name='guest_update'),
    path('guests/delete/<int:pk>/', GuestDeleteView.as_view(), name='guest_delete'),
    path('access_denied/', views.access_denied, name='access_denied'),
    path('reservations/download_excel/', views.download_excel, name='download_excel'),
]

publica/urls.py
from django.urls import path
from . import views
from .views import CustomLoginView, RegistroUsuarioView, ReservationCreateView, CustomLogoutView, VerificacionRegView, ReservaDetailView

urlpatterns = [
    path('', views.index, name="Inicio"),
    path('contact/',views.contact, name="contact"),
    path('aboutus/', views.aboutus, name="aboutus"),
    path('naturalpark/<int:naturalpark_id>/', views.campsites_by_naturalpark, name='campsites_by_naturalpark'),
    path('success/', views.success_view, name='success'),
    path('reservation/<int:campsite_id>/', ReservationCreateView.as_view(), name='reservation_campsite'),
    path('accounts/register/', RegistroUsuarioView.as_view(), name='register'),
    path('accounts/profile/', views.index, name='Inicio'),
    path('accounts/login/', CustomLoginView.as_view(), name='loginrn'),
    path('accounts/logout/', CustomLogoutView.as_view(), name='logoutrn'),
    path('register_verification/', VerificacionRegView.as_view(), name='register_verification'),
    path('categories/', views.categories, name="categories"),
    path('reserva_info/<int:pk>/', ReservaDetailView.as_view(), name='reserva_info'),
     path('error_page/', views.error_page, name='error_page'),
]

administracion/models.py
from django.utils import timezone
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    pass
class NaturalPark(models.Model):

    class Meta:
        db_table='Parques_Naturales'

    class Province(models.IntegerChoices):
        BUENOS_AIRES = 1, "Buenos Aires"
        CIUDAD_AUTONOMA_DE_BUENOS_AIRES = 2, "Ciudad Autónoma de Buenos Aires"
        CATAMARCA = 3, "Catamarca"
        CHACO = 4, "Chaco"
        CHUBUT = 5, "Chubut"
        CORDOBA = 6, "Córdoba"
        CORRIENTES = 7, "Corrientes"
        ENTRE_RIOS = 8, "Entre Ríos"
        FORMOSA = 9, "Formosa"
        JUJUY = 10, "Jujuy"
        SALTA = 11, "Salta"
        TUCUMAN = 12, "Tucumán"
        LA_PAMPA = 13, "La Pampa"
        LA_RIOJA = 14, "La Rioja"
        SAN_JUAN = 15, "San Juan"
        MENDOZA = 16, "Mendoza"
        MISIONES = 17, "Misiones"
        NEUQUEN = 18, "Neuquén"
        RIO_NEGRO = 19, "Río Negro"
        SAN_LUIS = 20, "San Luis"
        SANTA_CRUZ = 21, "Santa Cruz"
        SANTA_FE = 22, "Santa Fé"
        SANTIAGO_DEL_ESTERO = 23, "Santiago del Estero"
        TIERRA_DEL_FUEGO = 24, "Tierra del Fuego"


    name = models.CharField(max_length=255)
    description = models.TextField()
    location = models.CharField(max_length=255)
    province = models.IntegerField(choices=Province.choices)
    image = models.ImageField(upload_to='imagenes/', null=True)
    website = models.URLField(blank=True, null=True)

    def __str__(self):
        return f'Nombre: {self.name}'
    
class Category(models.Model):

    class Meta:
        db_table='Categorías'

    name = models.CharField(max_length=50, unique=True)
    description = models.TextField()
    capacity = models.IntegerField()
    price = models.FloatField(max_length=10)
    
    def __str__(self):
        return f'Nombre: {self.name}'
    
class Campsite(models.Model):

    class Meta:
        db_table='Campings'

    natural_park = models.ForeignKey(NaturalPark, on_delete=models.CASCADE, related_name='campsites')
    name = models.CharField(max_length=100)
    description = models.TextField()
    images = models.ImageField(upload_to='imagenes/', null=True)
    categories = models.ManyToManyField(Category, related_name='campsites')

    def __str__(self):
        return f'Nombre: {self.name}'

class Availability(models.Model):
    class Meta:
        db_table='Disponibilidades'

    campsite = models.ForeignKey(Campsite, on_delete=models.CASCADE, related_name='availabilities')
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)
    max_capacity=models.IntegerField(blank=True, null=True)

    def __str__(self):
        return f'Fecha inicio: {self.start_date}  Fecha fin: {self.end_date} Capacidad Máxima: {self.max_capacity}'
    
class Reservation(models.Model):
    class Meta:
        db_table='Reservas'
    
    code = models.CharField(max_length=8, unique=True)
    campsite = models.ForeignKey(Campsite, on_delete=models.CASCADE, related_name='reservations')
    availability = models.ForeignKey(Availability, on_delete=models.CASCADE)
    user = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    check_in = models.DateField()
    check_out = models.DateField()
    number_guests = models.IntegerField()
    total_cost = models.FloatField(max_length=10)
    reservation_date = models.DateTimeField(default=timezone.now, editable=False)

    def save(self, *args, **kwargs):
        if not self.code:
            self.code = uuid.uuid4().hex[:8].upper()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Código Reserva: {self.code} / Usuario: {self.user.first_name} {self.user.last_name}'

class Guest(models.Model):
    class Meta:
        db_table = 'Guests'

    reservation = models.ForeignKey(Reservation, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    dni = models.CharField(max_length=10)
    age = models.IntegerField()
    is_saved = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.reservation}'

class Profile(models.Model):
    class Meta:
        db_table="Perfiles"

    user = models.OneToOneField(Usuario, on_delete=models.CASCADE)
    phone = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    dni = models.CharField(max_length=255)
    is_client = models.BooleanField(default=True)

templates/administracion/parques_naturales/naturalpark_create.html
{% extends '../index_master.html' %} {% block content %}
<div
  class="center_col m-2 text-center bg-success rounded text-white"
  role="main"
>
  <h3>{% block title%} Crear un nuevo Parque Natural {% endblock%}</h3>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="border rounded p-4">
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit" class="btn btn-success">Guardar</button>
          <a href="{% url 'naturalpark_list' %}" class="btn btn-secondary"
            >Cancelar</a
          >
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/administracion/parques_naturales/naturalpark_delete.html
{% extends '../index_master.html' %} {% block content %}
<div
  class="center_col m-2 text-center bg-success rounded text-white"
  role="main"
>
  <h3>{% block title%} Eliminar un nuevo Parque Natural {% endblock%}</h3>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-12">
      <div class="border rounded p-2 text-center">
        <div
          class="d-flex justify-content-center align-items-center"
          style="height: 50vh"
        >
          <div class="col-md-6">
            <div
              class="border rounded p-3 bg-success text-white"
              style="opacity: 0.75"
            >
              <h2 class="mb-5">{{ naturalpark.name }}</h2>
              <h6 class="fw-bold mb-5">
                ¿Estás seguro de que querés borrar de la base de datos este
                parque natural?
              </h6>

              <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a href="{% url 'naturalpark_list' %}" class="btn btn-secondary"
                  >Cancelar</a
                >
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/administracion/parques_naturales/naturalpark_list.html
{% extends '../index_master.html' %} {% block content %}
<div class="center_col m-2 text-center bg-success rounded text-white" role="main">
  <h1>{% block title%} Parques Naturales {% endblock%}</h1>
</div>

<div class="d-flex justify-content-start align-items-center m-2" style="height: 20vh">
    <div class="col-md-6 d-flex">
      <div class="border p-2 rounded bg-success d-flex align-items-center" style="opacity: 0.75">
        <h5 class="text-white rounded me-1">Parque<i class="bi bi-flower2 ms-2"></i></h5> 
        <form method="GET" class="d-flex">
          {% csrf_token %}
          <div class="d-flex">
              {{ filter_form.name.label_tag }}
              {{ filter_form.name }}
          </div>
          <div><button type="submit" class="btn btn-primary ms-1"><i class="bi bi-search"></i></button></div>
      </form>
      </div>
    </div>
    <div class="col-md-2 p-2 justify-content-center align-items-center">
      {% if filter_form.name.errors %}
          <p class="text-danger fw-bold">{{ filter_form.name.errors|join:" " }}</p>
      {% endif %}
    </div>
  </div>

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-12">
        <div class="border rounded p-4">
          <a href="{% url 'naturalpark_create' %}" class="btn btn-sm btn-success text-white"
            ><i class="bi bi-file-earmark-plus me-2"></i>NUEVO - Parque Natural</a
          >
          <div class="table-responsive rounded mt-4" style="overflow-x: auto;">
          <table class="table">
            <thead>
              <tr>
                <th>Nombre</th>
                <th>Descripción</th>
                <th>Ubicación</th>
                <th>Provincia</th>
                <th>Imagen</th>
                <th>Sitio web</th>
                <th>Acciones</th>
              </tr>
            </thead>
            <tbody>
              {% for naturalpark in naturalparks %}
              <tr>
                <td>{{ naturalpark.name }}</td>
                <td>{{ naturalpark.description }}</td>
                <td>{{ naturalpark.location }}</td>
                <td>{{ naturalpark.get_province_display }}</td>
                <td>
                  <img
                    src="{{ naturalpark.image.url }}"
                    alt="Imagen"
                    width="100"
                  />
                </td>
                <td>
                  <a href="{{ naturalpark.website }}"
                    >{{ naturalpark.website }}</a
                  >
                </td>
                <td>
                  <div class="d-flex">
                  <a
                    href="{% url 'naturalpark_update' naturalpark.pk %}"
                    class="btn btn-info me-2" title="Editar"
                    ><i class="bi bi-pencil-fill"></i></a
                  >
                  <a href="{% url 'naturalpark_delete' naturalpark.pk %}" class="btn btn-danger" title="Eliminar">
                    <i class="bi bi-trash-fill"></i>
                  </a>
                </td>
              </div>
              </tr>
              {% empty %}
              <tr>
                <td colspan="5">No se encontraron parques naturales.</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% endblock %}
</div>

templates/administracion/parques_naturales/naturalpark_update.html
{% extends '../index_master.html' %} {% block content %}
<div
  class="center_col m-2 text-center bg-success rounded text-white"
  role="main"
>
  <h3>{% block title%} Actualizar un Parque Natural {% endblock%}</h3>
</div>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-6">
      <div class="border rounded p-4">
        <form method="POST">
          {% csrf_token %} {{ form.as_p }}
          <button type="submit" class="btn btn-info">Actualizar</button>
          <a href="{% url 'naturalpark_list' %}" class="btn btn-secondary"
            >Cancelar</a
          >
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}